version: "3"
services:
  web:
    image: nginx:1.17.6
    container_name: nginx_docker
    volumes:
      - "./web:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
  php:
    image: php:7.2.26-fpm
    container_name: php_docker
    restart: always
    volumes:
      - "./web:/var/www/html"
